### ISSUE TITLE
Conversion of anom to loli it's not perfect

### ISSUE THREAD

**Issue by BlawwNulled** [PurityWasHere/OpenBullet-Anomaly-Plugin#6]
it's not perfect because it doesn't change the post data and other things with `<USER> <PASS>`  to `<USERNAME> <PASSWORD>` which is the default one now on

**Comment by PurityWasHere** [comment]
That's the default that comes with OB, Although almost no one uses that environment file because 99% of configs use User:Pass instead. OpenBullet only comes with that because of legal reasons. It's highly recommended to change your environment.ini file to the version anomaly used as it is almost required for compatibility
